### ISSUE TITLE
Implement Heizkörperregler

### ISSUE THREAD

**Issue by michaelosthege** [michaelosthege/AvmSmartHome#4]

**Comment by DoCode** [comment]
Any news on this feature?

**Comment by DoCode** [comment]
Ok, I see...
The methods/REST calls already defined.

**Comment by michaelosthege** [comment]
Sorry, I did not notice the notification.
It's been a while, but it seems that get/set of Spar-/Soll-/Komfort-temperature are implemented in [SessionInfo.cs](https://github.com/michaelosthege/AvmSmartHome/blob/49be3e23d8d417b5a741158c113039e9cb05e658/AvmSmartHome.NET/SessionInfo.cs#L287)

At the time, I did not have a HKR to test it.  If you find/fix bugs, I can merge them.

**Comment by lazou** [comment]
hi, i have created a pull request #6 to enhance the device class with addtional stuff like HKR. It is working with Comet DECT HKR devices and Magenta Smarthome Door-Window-Sensors.
